### ISSUE TITLE
About the build type

### ISSUE THREAD

**Issue by netw0rkf10w** [MiguelMonteiro/permutohedral_lattice#10]
Hi Miguel,

I noticed that in the build script you used cmake to build the project in debug mode: `cmake -DCMAKE_BUILD_TYPE=Debug`.

Should we expect better performance if we build it in release mode? I tried setting `-DCMAKE_BUILD_TYPE=Release` but this produced errors.

Sorry if the question is stupid.

Thank you in advance for your answer!

**Comment by MiguelMonteiro** [comment]
Which kind of errors?
I have never changed that flag, maybe it makes a difference... 
Although, I think that either:
That flag is for the C++ CPU code and therefore since the main computation is done on GPU there wouldn't be much of a difference.
OR
That flag is for the compiler and it only changes the speed of compilation.
Might be wrong though

**Comment by netw0rkf10w** [comment]
Hi Miguel,

Sorry I have just tried it again and it works. I'm not sure what happened when I first tried it.

I confirm that changing this flag does not improve the computation speed at all.
