### ISSUE TITLE
Cuda Debug informations

### ISSUE THREAD

**Issue by Fettpet** [MiguelMonteiro/permutohedral_lattice#5]
Hello,

inside the memory allocator on line [96](https://github.com/MiguelMonteiro/permutohedral_lattice/blob/master/src/DeviceMemoryAllocator.h#L96), [102](https://github.com/MiguelMonteiro/permutohedral_lattice/blob/master/src/DeviceMemoryAllocator.h#L102) and [106](https://github.com/MiguelMonteiro/permutohedral_lattice/blob/master/src/DeviceMemoryAllocator.h#L106) are naked cuda calls. They doesn't deliver any debug information. For example if the gpu rans out of memory the program exists when it checks the [createLattice](https://github.com/MiguelMonteiro/permutohedral_lattice/blob/master/src/PermutohedralLatticeGPU.cuh#L462) function. This is a hard to find error. A simple solution would be to integrate some checks after the cuda calls.

greets Sebastian

**Comment by MiguelMonteiro** [comment]
Thanks for pointing it out. 
If you are using the code within Tensoflow that is not a problem because the memory allocation is handled by Tensorflow.
This is only a problem if you are using this as a standalone package.
I will fix it when I get the time or if you would like to help me out please submit a pull request.

Best,

Miguel

**Comment by Fettpet** [comment]
Hey Miguel,
I like to help you. I create a pull request in the next days. I use the Permutohedral Lattice for a pytorch backend.

greets Sebastian

**Comment by MiguelMonteiro** [comment]
Thanks,

I don't know how the pytorch GPU memory allocation works? Does it have its own allocator or does it rely on C++ allocation?
In Tensorflow, the Tensorflow memory allocator allocates most of the GPU memory (like 95%) at beginning independently of whether its needed or not. Because of this, when I was using C++ allocation instead of the Tensorflow allocator I would always run out of memory.
You should check whether this is the case in pytorch.

Best,

Miguel
