### ISSUE TITLE
Permutohedral Lattice for 3D pointcloud

### ISSUE THREAD

**Issue by hasanari** [MiguelMonteiro/permutohedral_lattice#9]
Hi,

Thanks for your work in this repo. I am currently implementing CRF-RNN for 3D pointcloud, but it's very hard for me to understand the Permutohedral Lattice. I decided to implement CRF-RNN without the lattice, but it seems very slow and the improvement is not significant.

Would you be kind to point me, how to hack the lattice implementation for 3D points?
It has X,Y,Z as spatial feature and Intensity as non-spatial feature, so it would be at least 4D.

Hasan

**Comment by MiguelMonteiro** [comment]
You mean you tried to use brute froce implementations of the gaussian and bileteral filters?
This is a bad idea since the brute force implementation is O(N^2), where N is the number of pixels.
The permutohedral lattice approximates these filters in O(N).
Just compile this code with SPATIAL_DIMS=3 and NUM_REFERENCE_CHANNELS=1, should do what you need.
Also advise reading the lattice paper and brush up on bilateral filtering.

**Comment by hasanari** [comment]
> This is a bad idea since the brute force implementation is O(N^2), where N is the number of pixels.

True, but when I do it in matrix space, it's not so expensive. I do read the lattice paper, but it still confuses me.

> Just compile this code with SPATIAL_DIMS=3 and NUM_REFERENCE_CHANNELS=1, should do what you need.

Will do, hopefully it works.

**Comment by MiguelMonteiro** [comment]
> True, but when I do it in matrix space, it's not so expensive. I do read the lattice paper, but it still confuses me.

What do you mean it's not so expensive, there is no way around it, if you do brute force you cannot escaper O(N^2). Don't worry if it still confuses you, it also took me a long time to understand it and still confuses me a bit :)
